### ISSUE TITLE
Metadata generation failed 

### ISSUE THREAD

**Issue by GiganticThirstyHerald** [domarm-comat/pyqt6rc#3]
```
Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      Traceback (most recent call last):
        File "C:\Users\User\Documents\Folder\App\App\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 156, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
     
      During handling of the above exception, another exception occurred:
     
      Traceback (most recent call last):
        File "C:\Users\User\Documents\Folder\App\App\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\User\Documents\Folder\App\App\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\User\Documents\Folder\App\App\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 160, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-9jq43ib6\overlay\Lib\site-packages\sipbuild\api.py", line 46, in build_wheel
          project = AbstrAppProject.bootstrap('wheel',
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-9jq43ib6\overlay\Lib\site-packages\sipbuild\abstrApp_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-9jq43ib6\overlay\Lib\site-packages\sipbuild\project.py", line 584, in setup
          self.apply_user_defaults(tool)
        File "C:\Users\User\AppData\Local\Temp\pip-install-xs0syto6\pyqt6_65df5732e0234d02be63f91e8cec5600\project.py", line 60, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-9jq43ib6\overlay\Lib\site-packages\pyqtbuild\project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-9jq43ib6\overlay\Lib\site-packages\sipbuild\project.py", line 236, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-9jq43ib6\overlay\Lib\site-packages\pyqtbuild\builder.py", line 67, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

**Comment by domarm-comat** [comment]
Can You give me some context? It seems like it's problem with Pyqt6 installation.
Try:
```python3 -m pip install pip setuptools --upgrade```

Or:
```python3 -m pip install pip setuptools --upgrade && pip3 install PyQt6```

**Comment by GiganticThirstyHerald** [comment]
> 
Oh sorry, my bad - I've accidentally replaced my comments with the code
I was trying to install module with pip install pyqt6rc, win10, PyQt6 in virtual environment

I've updated modules like you'd suggested, but still got this error

**Comment by domarm-comat** [comment]
Ok, doing some looking around, I believe Your problem is, that You don't have "qmake" installed. This is usually bundled with Qt6 installation (https://www.qt.io/download). I assume You already has Qt6 installed, right?

Try to execute qmake.exe in Your cmdline, it should be available. Make sure qmake.exe is in Your Windows PATH, so that compiler can find it.

This is quote from PyQt6 package (https://pypi.org/project/PyQt6/):
```pip will also build and install the bindings from the sdist package but Qt’s qmake tool must be on PATH.```
